### PR TITLE
added input and textarea component

### PR DESCRIPTION
**Pull request by DivyanshSareen**
added input and text-area components

### CODE REVIEW

**Comment by DivyanshSareen** [comment]
preview link: https://deploy-preview-6--peaceui.netlify.app/input (the default preview link not working)

**Review by archit7448 — APPROVED** [review]
looks good to merge

**Comment by Muzammil-khan710** [comment]
Good to merge !

**Review by Muzammil-khan710 — APPROVED** [review]
Good to merge

**Pull request merged**
